title: My amaxing course
description: A description of your course
template:
  repo: my-amaxing-course-template
  name: my-amaxing-course
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
